FROM replaced-by-buildconfig
# Baseline Dockerfile for layering repos atop an ART image to construct an
# ART equivalent image.
# Used as a template for 'images:streams gen-buildconfigs'

# TODO: DELETE - testing only, marks images built through this transform
ENV ART_CI_TRANSFORM_TEST=centos_stream8
